### ISSUE TITLE
ThatLilCoderGal doesnt know how to code

### ISSUE THREAD

**Issue by DetachHead** [ThatLilCoderGal/repo#1]
despite having "Coder" in her user name, "ThatLilCoderGal" doesn't actually know how to code, so this entire repo has probably been plagiarized from a more talented user, perhaps with a username like "ThatLilCoderGuy"

**Comment by ThatLilCoderGal** [comment]
check this out 
function suht up {
if name = DetachHead
shut uop}

that's my code I did it just now and it is flawless

**Comment by ThatLilCoderGal** [comment]
sorry didnt mean to do that

**Comment by shitpostbotmin** [comment]
- [x] detach head own status

**Comment by DetachHead** [comment]
![image](https://user-images.githubusercontent.com/57028336/87414317-f5913f00-c60e-11ea-90a1-07470740aff1.png)

* [x] shitpostbotmin owned status
